projects:
  Auth:
    schema: ./src/graphql/schema/auth.graphql
    extensions:
      endpoints:
        Auth:
          url: https://api.hikit.io/auth/
          headers:
            user-agent: JS GraphQL
          introspect: false
    documents:
      - ./src/graphql/auth.graphql
  Other:
    schema: ./src/graphql/schema/service.graphql
    extensions:
      endpoints:
        Proxy:
          url: https://api.hikit.io/proxy/
          headers:
            user-agent: JS GraphQL
          introspect: false
    documents:
      - ./src/graphql/service.graphql